// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqzR6zNPVBwjg8bZxAhS8CcXPRjabqzA',
    appId: '1:635469629055:web:b72ebc1a7648d5156fe14a',
    messagingSenderId: '635469629055',
    projectId: 'intrst-1525412155568',
    authDomain: 'intrst-1525412155568.firebaseapp.com',
    storageBucket: 'intrst-1525412155568.appspot.com',
    measurementId: 'G-59D7JN4GHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KD_MOtRG_ttZJ2PBi_plX7g2uumFv6c',
    appId: '1:635469629055:android:3e95f8602d08b7ab6fe14a',
    messagingSenderId: '635469629055',
    projectId: 'intrst-1525412155568',
    storageBucket: 'intrst-1525412155568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDETwowgdyzw4pCWLnm_MS4PrajmexEY4A',
    appId: '1:635469629055:ios:b5ddc1843280515e6fe14a',
    messagingSenderId: '635469629055',
    projectId: 'intrst-1525412155568',
    storageBucket: 'intrst-1525412155568.appspot.com',
    iosBundleId: 'app.intrst.nameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDETwowgdyzw4pCWLnm_MS4PrajmexEY4A',
    appId: '1:635469629055:ios:94e2777f5a49f80e6fe14a',
    messagingSenderId: '635469629055',
    projectId: 'intrst-1525412155568',
    storageBucket: 'intrst-1525412155568.appspot.com',
    iosBundleId: 'app.intrst.nameApp.RunnerTests',
  );
}
